# Site Settings
title: Igor Šinkovec — CV
description: Senior Full-Stack Engineer
url: https://igor.sinkovec.cc
baseurl: ""

# Theme
remote_theme: sharu725/online-cv

# Color skin: blue | turquoise | green | berry | orange | ceramic
theme_skin: turquoise

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Build
permalink: pretty
encoding: utf-8
compress_html:
  clippings: all
  ignore:
    envs: development

plugins:
  - jekyll-remote-theme
